name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'release/**'
  pull_request:

  workflow_dispatch:

jobs:
  quality:
    strategy:
      matrix:
        node: ['18']
        os: [linux]
    runs-on: ubuntu-latest
    name: Quality (${{matrix.os}}, Node ${{matrix.node}})
    steps:
      - name: Github setup & checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js ${{matrix.node}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}

      - name: CI Build & Install
        run: npm ci

      - name: Lint Checks
        run: npm run lint

  hub-tests:
    needs: quality
    strategy:
      matrix:
        node: ['18']
    runs-on: ubuntu-latest
    name: Test (${{matrix.hub}})
    steps:
      - name: Github setup & checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js ${{matrix.node}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}

      - name: CI Build & Install
        run: npm ci

      - name: Test ${{matrix.hub}}
        run: |
          npm run test
